# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
    ignore:
      - dependency-name: "*" # This will ignore all dependencies
        update-types: ["version-update:semver-patch"]