services:
  zwd-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zaken-frontend
    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-salmagundi/zwd-frontend}:${VERSION:-latest}
    ports:
      - "8081:8000"
