/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["api_schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/address/{id}/homeowner-association/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["address_homeowner_association_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/address/{id}/mijn-amsterdam/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Retrieve the address details, Homeowner Association (vve) and related cases for a given BAG ID.
         *     This endpoint is specifically intended for use by the "Mijn Amsterdam" platform.
         */
        get: operations["address_mijn_amsterdam_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/advisors/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["advisors_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/advisors/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["advisors_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bpmn-models/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all BPMN model names */
        get: operations["bpmn_models_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bpmn-models/{model_name}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get versions and filenames for a specific model */
        get: operations["bpmn_models_list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bpmn-models/{model_name}/file/{version}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a specific BPMN workflow file */
        get: operations["bpmn_models_file_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/case-close/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["case_close_list"];
        put?: never;
        post: operations["case_close_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/case-close/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["case_close_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/case-close/reasons/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve reasons to close a case */
        get: operations["case_close_reasons_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/case-statuses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["case_statuses_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/case-statuses/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["case_statuses_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cases_list"];
        put?: never;
        post: operations["cases_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cases_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{id}/advisor/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Update the advisor for a case */
        patch: operations["cases_advisor_partial_update"];
        trace?: never;
    };
    "/api/v1/cases/{id}/advisors/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Update the advisor for a case */
        get: operations["cases_advisors_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{id}/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cases_documents_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{id}/documents/{doc_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["cases_documents_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{id}/documents/{doc_id}/update-name/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Update the name of a document */
        patch: operations["cases_documents_update_name_partial_update"];
        trace?: never;
    };
    "/api/v1/cases/{id}/documents/download/{doc_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cases_documents_download_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{id}/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cases_events_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{id}/processes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve workflow options */
        get: operations["cases_processes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{id}/processes/start/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Start subworkflow */
        post: operations["cases_processes_start_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{id}/workflow-instances/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve all workflow instances for this case, including completed ones and those without open tasks. */
        get: operations["cases_workflow_instances_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{id}/workflows/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cases_workflows_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cases_documents_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/legacy/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve case by legacy id */
        get: operations["cases_legacy_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/districts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["districts_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/districts/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["districts_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generic-tasks/complete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Complete GenericCompletedTask */
        post: operations["generic_tasks_complete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generic-tasks/complete-file-task/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generic_tasks_complete_file_task_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/homeowner-association/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["homeowner_association_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/homeowner-association/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["homeowner_association_retrieve"];
        put: operations["homeowner_association_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["homeowner_association_partial_update"];
        trace?: never;
    };
    "/api/v1/homeowner-association/{id}/apartments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["homeowner_association_apartments_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/homeowner-association/{id}/cases/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["homeowner_association_cases_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/homeowner-association/{id}/communication-notes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List communication notes for a homeowner association */
        get: operations["homeowner_association_communication_notes_list"];
        put?: never;
        /** @description Create a communication note for a homeowner association */
        post: operations["homeowner_association_communication_notes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/homeowner-association/{id}/communication-notes/{note_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Delete a communication note */
        delete: operations["homeowner_association_communication_notes_destroy"];
        options?: never;
        head?: never;
        /** @description Update a communication note */
        patch: operations["homeowner_association_communication_notes_partial_update"];
        trace?: never;
    };
    "/api/v1/homeowner-association/{id}/contacts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["homeowner_association_contacts_retrieve"];
        put: operations["homeowner_association_contacts_update"];
        post: operations["homeowner_association_contacts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/homeowner-association/{id}/delete-contact/{contact_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["homeowner_association_delete_contact_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/homeowner-association/{id}/subsidy/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve subsidy applications for a homeowner association */
        get: operations["homeowner_association_subsidy_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/homeowner-association/import-course-participants/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Import course participants from a CSV file */
        post: operations["homeowner_association_import_course_participants_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/homeowner-association/import-letters/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Import letters from a CSV file */
        post: operations["homeowner_association_import_letters_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/homeowner-association/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["homeowner_association_search_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/neighborhoods/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["neighborhoods_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/neighborhoods/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["neighborhoods_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tasks_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tasks_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/names/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return distinct open task names for dropdown filtering. */
        get: operations["tasks_names_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wijken/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["wijken_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wijken/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["wijken_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivationTeam: {
            type?: components["schemas"]["ActivationTeamTypeEnum"];
            subject?: string | null;
            /** Format: date */
            meeting_date?: string | null;
        };
        /**
         * @description * `Informatiebijeenkomst` - INFORMATIEBIJEENKOMST
         *     * `Ledenvergadering` - LEDENVERGADERING
         * @enum {string}
         */
        ActivationTeamTypeEnum: "Informatiebijeenkomst" | "Ledenvergadering";
        /**
         * @description * `Energieadvies` - ENERGY_ADVICE
         *     * `Haalbaarheidsonderzoek` - HBO
         *     * `Energieadvies (OUD)` - OLD_ENERGY_ADVICE
         *     * `Zon-Advies (OUD)` - OLD_SOLAR_ADVICE
         * @enum {string}
         */
        AdviceTypeEnum: "Energieadvies" | "Haalbaarheidsonderzoek" | "Energieadvies (OUD)" | "Zon-Advies (OUD)";
        Apartment: {
            straatnaam?: string | null;
            huisnummer?: number | null;
            huisletter?: string | null;
            huisnummertoevoeging?: string | null;
            postcode?: string | null;
            woonplaats?: string | null;
            adresseerbaarobject_id?: string | null;
            nummeraanduiding_id?: string | null;
            eigenaar_type?: string | null;
            eigenaar_naam?: string | null;
        };
        /**
         * @description * `Advies` - ADVICE
         *     * `Activatieteam` - ACTIVATIONTEAM
         * @enum {string}
         */
        ApplicationTypeEnum: "Advies" | "Activatieteam";
        /** @enum {unknown} */
        BlankEnum: "";
        BpmnModel: {
            version: string;
            file_name: string;
            model: string;
        };
        Case: {
            activation_team?: components["schemas"]["ActivationTeam"];
            advice_type?: (components["schemas"]["AdviceTypeEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            application_type?: components["schemas"]["ApplicationTypeEnum"];
            /** Format: date-time */
            created?: string;
            description?: string | null;
            /** Format: date */
            end_date?: string | null;
            homeowner_association: components["schemas"]["CaseHomeownerAssociation"];
            readonly id: number;
            legacy_id?: string | null;
            prefixed_dossier_id?: string | null;
            /** Format: date */
            request_date?: string;
            readonly advisor: components["schemas"]["CaseAdvisor"];
            readonly status: string;
            workflows: components["schemas"]["CaseWorkflow"][];
        };
        CaseAdvisor: {
            readonly id: number;
            name: string;
        };
        CaseClose: {
            readonly id: number;
            case_user_task_id?: string;
            description?: string | null;
            /** Format: date-time */
            readonly created: string;
            case: number;
            reason: number;
        };
        CaseCloseReason: {
            readonly id: number;
            name: string;
            is_successful: boolean;
        };
        CaseCreate: {
            activation_team?: components["schemas"]["ActivationTeam"];
            advice_type?: (components["schemas"]["AdviceTypeEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            application_type?: components["schemas"]["ApplicationTypeEnum"];
            contacts?: components["schemas"]["Contact"][];
            description?: string | null;
            homeowner_association?: number | null;
            readonly id: number;
            legacy_id?: string | null;
            /** Format: date */
            request_date?: string;
        };
        CaseDocument: {
            readonly id: number;
            case: number;
            /** Format: uri */
            document: string;
            name: string;
            /** Format: date-time */
            readonly created: string;
        };
        CaseDocumentNameUpdate: {
            name: string;
        };
        CaseDocumentWithTask: {
            readonly id: number;
            case: number;
            /** Format: uri */
            document: string;
            name: string;
            /** Format: date-time */
            readonly created: string;
            case_user_task_id?: string | null;
        };
        CaseEvent: {
            readonly id: number;
            event_values: {
                [key: string]: unknown;
            };
            event_variables: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            readonly created: string;
            type: components["schemas"]["CaseEventTypeEnum"];
            emitter_id: number;
            case: number;
        };
        /**
         * @description * `CASE` - CASE
         *     * `CASE_CLOSE` - CASE_CLOSE
         *     * `GENERIC_TASK` - GENERIC_TASK
         * @enum {string}
         */
        CaseEventTypeEnum: "CASE" | "CASE_CLOSE" | "GENERIC_TASK";
        CaseHomeownerAssociation: {
            readonly id: number;
            name: string;
            readonly district: string;
            readonly neighborhood: string;
            number_of_apartments: number;
        };
        CaseList: {
            advice_type?: (components["schemas"]["AdviceTypeEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly advisor: string;
            application_type?: components["schemas"]["ApplicationTypeEnum"];
            /** Format: date-time */
            created?: string;
            /** Format: date */
            end_date?: string | null;
            homeowner_association: components["schemas"]["CaseHomeownerAssociation"];
            readonly id: number;
            legacy_id?: string | null;
            prefixed_dossier_id?: string | null;
            /** Format: date */
            request_date?: string;
            readonly status: string;
            /** Format: date-time */
            readonly updated: string;
        };
        CaseStatus: {
            name: string;
        };
        CaseUserTask: {
            readonly id: number;
            /** Format: uuid */
            task_id: string;
            task_name: string;
            name: string;
            form?: unknown;
            roles?: string[] | null;
            /** Format: date-time */
            due_date: string;
            owner?: number | null;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly updated: string;
            completed?: boolean;
            case: number;
            readonly homeowner_association: string;
            readonly initiated_by: string;
            /** @description Indicates whether this task requires review by another user. */
            requires_review?: boolean;
        };
        CaseUserTaskList: {
            readonly id: number;
            name: string;
            case: components["schemas"]["CaseList"];
            /** Format: date-time */
            readonly created: string;
        };
        CaseWorkflow: {
            readonly id: number;
            case?: number | null;
            readonly tasks: components["schemas"]["CaseUserTask"][];
            completed?: boolean;
        };
        CaseWorkflowInstance: {
            readonly id: number;
            workflow_type?: string | null;
            workflow_version?: string | null;
            completed?: boolean;
            main_workflow?: boolean;
            readonly current_task_specs: string[];
        };
        Contact: {
            readonly id: number;
            fullname: string;
            /** Format: email */
            email: string;
            phone: string;
            role: string;
            is_primary?: boolean;
            /** Format: date */
            course_date?: string | null;
        };
        /** @description Serializer for course participant CSV import requests */
        CourseParticipantImport: {
            /** Format: uri */
            file: string;
        };
        District: {
            readonly id: number;
            name: string;
            readonly neighborhoods: components["schemas"]["Neighborhood"][];
        };
        /** @description Serializer for failed rows data structure */
        FailedRowsData: {
            headers: string[];
            rows: {
                [key: string]: string;
            }[];
        };
        GenericCompletedTaskCreate: {
            readonly id: number;
            case_user_task_id: string;
            case: number;
            variables: unknown;
            description?: string;
            /** Format: date-time */
            readonly date_added: string;
        };
        HomeownerAssociation: {
            annotation?: string | null;
            beschermd_stadsdorpsgezicht?: string | null;
            build_year: number;
            readonly contacts: components["schemas"]["Nested"][];
            readonly course_participant_count: string;
            readonly district: string;
            readonly id: number;
            is_priority_neighborhood: boolean;
            is_small: boolean;
            kvk_nummer?: string | null;
            ligt_in_beschermd_gebied?: string | null;
            monument_status?: string | null;
            name: string;
            readonly neighborhood: string;
            number_of_apartments: number;
            owners?: components["schemas"]["Owner"][];
            readonly wijk: string;
            zip_code?: string | null;
            readonly letter_count: string;
            readonly advice_cases_count: string;
            readonly activationteam_cases_count: string;
        };
        HomeownerAssociationCommunicationNote: {
            readonly id: number;
            note: string;
            author_name?: string;
            /** Format: date-time */
            date?: string | null;
        };
        HomeownerAssociationCommunicationNoteCreate: {
            readonly id: number;
            note: string;
            author_name?: string;
            /** Format: date-time */
            date?: string | null;
        };
        HomeownerAssociationUpdate: {
            annotation?: string | null;
        };
        /** @description Serializer for CSV import results */
        ImportResult: {
            counts: {
                [key: string]: number;
            };
            messages: string[];
            warnings: string[];
            errors: components["schemas"]["RowError"][];
            failed_rows_data?: components["schemas"]["FailedRowsData"] | null;
        };
        /** @description Serializer for letter CSV import requests */
        LetterImport: {
            /** Format: uri */
            file: string;
            /** Format: date-time */
            date: string;
            description: string;
            author_name: string;
        };
        MijnAmsterdam: {
            bag_id: string;
            beschermd_stadsdorpsgezicht?: string | null;
            build_year: number;
            district?: string | null;
            kvk_nummer?: string | null;
            ligt_in_beschermd_gebied?: string | null;
            monument_status?: string | null;
            name: string;
            neighborhood?: string | null;
            number_of_apartments: number;
            wijk?: string | null;
            zip_code?: string | null;
            cases: components["schemas"]["MijnAmsterdamCaseList"][];
        };
        MijnAmsterdamCaseList: {
            activation_team?: components["schemas"]["ActivationTeam"];
            advice_type?: (components["schemas"]["AdviceTypeEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            application_type?: components["schemas"]["ApplicationTypeEnum"];
            /** Format: date-time */
            created?: string;
            /** Format: date */
            end_date?: string | null;
            homeowner_association: components["schemas"]["CaseHomeownerAssociation"];
            readonly id: number;
            legacy_id?: string | null;
            prefixed_dossier_id?: string | null;
            /** Format: date */
            request_date?: string;
            readonly status: string;
            /** Format: date-time */
            readonly updated: string;
        };
        Neighborhood: {
            readonly id: number;
            name: string;
        };
        Nested: {
            readonly id: number;
            /** Format: email */
            email: string;
            phone: string;
            fullname: string;
            role: string;
            is_primary?: boolean;
            /** Format: date */
            course_date?: string | null;
            homeowner_association: number;
        };
        /** @enum {unknown} */
        NullEnum: null;
        Owner: {
            type: string;
            name?: string | null;
            number_of_apartments: number;
        };
        PaginatedCaseCloseList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CaseClose"][];
        };
        PaginatedCaseListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CaseList"][];
        };
        PaginatedCaseStatusList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["CaseStatus"][];
        };
        PaginatedCaseUserTaskListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CaseUserTaskList"][];
        };
        PaginatedDistrictList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["District"][];
        };
        PaginatedHomeownerAssociationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["HomeownerAssociation"][];
        };
        PaginatedNeighborhoodList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["Neighborhood"][];
        };
        PaginatedWijkList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["Wijk"][];
        };
        PatchedCaseDocumentNameUpdate: {
            name?: string;
        };
        PatchedHomeownerAssociationCommunicationNoteUpdate: {
            note?: string;
            author_name?: string;
            /** Format: date-time */
            date?: string | null;
        };
        PatchedHomeownerAssociationUpdate: {
            annotation?: string | null;
        };
        PatchedUpdateCaseAdvisor: {
            advisor?: number;
        };
        /** @description Serializer for individual row errors from CSV imports */
        RowError: {
            row_number: number;
            field?: string | null;
            message: string;
        };
        StartWorkflow: {
            workflow_option_id: number;
        };
        SubsidyItem: {
            id: number;
            dossiernummer: string;
            aanvrager: string;
            regelingnaam: string;
            beleidsterrein?: string | null;
            organisatieonderdeel?: string | null;
            projectnaam?: string | null;
            typePeriodiciteit?: string | null;
            /** Format: decimal */
            bedragAangevraagd?: string | null;
            /** Format: decimal */
            bedragVerleend?: string | null;
            /** Format: date */
            publicatiedatumVerleningsbesluit?: string | null;
            /** Format: decimal */
            bedragVastgesteld?: string | null;
            /** Format: date */
            publicatiedatumVaststellingsbesluit?: string | null;
            subsidiejaar?: number | null;
            /** Format: date */
            datumOverzicht?: string | null;
        };
        Wijk: {
            readonly id: number;
            name: string;
        };
        WorkflowOption: {
            readonly id: number;
            name: string;
            message_name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    address_homeowner_association_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeownerAssociation"];
                };
            };
        };
    };
    address_mijn_amsterdam_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MijnAmsterdam"];
                };
            };
        };
    };
    advisors_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseAdvisor"][];
                };
            };
        };
    };
    advisors_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this advisor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseAdvisor"];
                };
            };
        };
    };
    bpmn_models_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    bpmn_models_list_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BpmnModel"][];
                };
            };
        };
    };
    bpmn_models_file_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_name: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    case_close_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCaseCloseList"];
                };
            };
        };
    };
    case_close_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseClose"];
                "application/x-www-form-urlencoded": components["schemas"]["CaseClose"];
                "multipart/form-data": components["schemas"]["CaseClose"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseClose"];
                };
            };
        };
    };
    case_close_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this case close. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseClose"];
                };
            };
        };
    };
    case_close_reasons_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseCloseReason"];
                };
            };
        };
    };
    case_statuses_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCaseStatusList"];
                };
            };
        };
    };
    case_statuses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Status. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseStatus"];
                };
            };
        };
    };
    cases_list: {
        parameters: {
            query?: {
                /**
                 * @description * `Energieadvies` - ENERGY_ADVICE
                 *     * `Haalbaarheidsonderzoek` - HBO
                 *     * `Energieadvies (OUD)` - OLD_ENERGY_ADVICE
                 *     * `Zon-Advies (OUD)` - OLD_SOLAR_ADVICE
                 */
                advice_type?: "Energieadvies" | "Energieadvies (OUD)" | "Haalbaarheidsonderzoek" | "Zon-Advies (OUD)" | null;
                advisor?: number[];
                /**
                 * @description * `Advies` - ADVICE
                 *     * `Activatieteam` - ACTIVATIONTEAM
                 */
                application_type?: "Activatieteam" | "Advies";
                closed?: boolean;
                district?: string[];
                end_date_range_after?: string;
                end_date_range_before?: string;
                /** @description If true, includes all nested properties in the response. */
                expand?: boolean;
                /** @description HOA has <= 12 apartments */
                is_small_hoa?: boolean;
                neighborhood?: string[];
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                request_date_range_after?: string;
                request_date_range_before?: string;
                /** @description Search */
                search?: string;
                status?: string[];
                wijk?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCaseListList"];
                };
            };
        };
    };
    cases_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CaseCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["CaseCreate"];
                "multipart/form-data": components["schemas"]["CaseCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseCreate"];
                };
            };
        };
    };
    cases_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this case. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
        };
    };
    cases_advisor_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this case. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUpdateCaseAdvisor"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUpdateCaseAdvisor"];
                "multipart/form-data": components["schemas"]["PatchedUpdateCaseAdvisor"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    cases_advisors_list: {
        parameters: {
            query?: {
                /**
                 * @description * `Energieadvies` - ENERGY_ADVICE
                 *     * `Haalbaarheidsonderzoek` - HBO
                 *     * `Energieadvies (OUD)` - OLD_ENERGY_ADVICE
                 *     * `Zon-Advies (OUD)` - OLD_SOLAR_ADVICE
                 */
                advice_type?: "Energieadvies" | "Energieadvies (OUD)" | "Haalbaarheidsonderzoek" | "Zon-Advies (OUD)" | null;
                advisor?: number[];
                /**
                 * @description * `Advies` - ADVICE
                 *     * `Activatieteam` - ACTIVATIONTEAM
                 */
                application_type?: "Activatieteam" | "Advies";
                closed?: boolean;
                district?: string[];
                end_date_range_after?: string;
                end_date_range_before?: string;
                /** @description HOA has <= 12 apartments */
                is_small_hoa?: boolean;
                neighborhood?: string[];
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                request_date_range_after?: string;
                request_date_range_before?: string;
                /** @description Search */
                search?: string;
                status?: string[];
                wijk?: string[];
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this case. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseAdvisor"][];
                };
            };
        };
    };
    cases_documents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this case. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDocument"];
                };
            };
        };
    };
    cases_documents_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
                /** @description A unique integer value identifying this case. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cases_documents_update_name_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
                /** @description A unique integer value identifying this case. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCaseDocumentNameUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCaseDocumentNameUpdate"];
                "multipart/form-data": components["schemas"]["PatchedCaseDocumentNameUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDocumentNameUpdate"];
                };
            };
        };
    };
    cases_documents_download_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
                /** @description A unique integer value identifying this case. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
        };
    };
    cases_events_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this case. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseEvent"];
                };
            };
        };
    };
    cases_processes_list: {
        parameters: {
            query?: {
                /**
                 * @description * `Energieadvies` - ENERGY_ADVICE
                 *     * `Haalbaarheidsonderzoek` - HBO
                 *     * `Energieadvies (OUD)` - OLD_ENERGY_ADVICE
                 *     * `Zon-Advies (OUD)` - OLD_SOLAR_ADVICE
                 */
                advice_type?: "Energieadvies" | "Energieadvies (OUD)" | "Haalbaarheidsonderzoek" | "Zon-Advies (OUD)" | null;
                advisor?: number[];
                /**
                 * @description * `Advies` - ADVICE
                 *     * `Activatieteam` - ACTIVATIONTEAM
                 */
                application_type?: "Activatieteam" | "Advies";
                closed?: boolean;
                district?: string[];
                end_date_range_after?: string;
                end_date_range_before?: string;
                /** @description HOA has <= 12 apartments */
                is_small_hoa?: boolean;
                neighborhood?: string[];
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                request_date_range_after?: string;
                request_date_range_before?: string;
                /** @description Search */
                search?: string;
                status?: string[];
                wijk?: string[];
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this case. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowOption"][];
                };
            };
        };
    };
    cases_processes_start_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this case. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Case"];
                "application/x-www-form-urlencoded": components["schemas"]["Case"];
                "multipart/form-data": components["schemas"]["Case"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartWorkflow"];
                };
            };
        };
    };
    cases_workflow_instances_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this case. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseWorkflowInstance"][];
                };
            };
        };
    };
    cases_workflows_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this case. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
        };
    };
    cases_documents_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseDocument"];
                "application/x-www-form-urlencoded": components["schemas"]["CaseDocument"];
                "multipart/form-data": components["schemas"]["CaseDocument"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDocument"];
                };
            };
        };
    };
    cases_legacy_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this case. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseList"];
                };
            };
        };
    };
    districts_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDistrictList"];
                };
            };
        };
    };
    districts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Stadsdeel. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["District"];
                };
            };
        };
    };
    generic_tasks_complete_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenericCompletedTaskCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["GenericCompletedTaskCreate"];
                "multipart/form-data": components["schemas"]["GenericCompletedTaskCreate"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generic_tasks_complete_file_task_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseDocumentWithTask"];
                "application/x-www-form-urlencoded": components["schemas"]["CaseDocumentWithTask"];
                "multipart/form-data": components["schemas"]["CaseDocumentWithTask"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDocumentWithTask"];
                };
            };
        };
    };
    homeowner_association_list: {
        parameters: {
            query?: {
                /** @description Minimum number of course participants */
                course_participant_count?: number;
                district?: string[];
                /** @description HOA has <= 12 apartments */
                is_small_hoa?: boolean;
                /** @description Minimum number of letters sent */
                letter_count?: number;
                neighborhood?: string[];
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description Search */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedHomeownerAssociationList"];
                };
            };
        };
    };
    homeowner_association_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this homeowner association. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeownerAssociation"];
                };
            };
        };
    };
    homeowner_association_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this homeowner association. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["HomeownerAssociationUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["HomeownerAssociationUpdate"];
                "multipart/form-data": components["schemas"]["HomeownerAssociationUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeownerAssociationUpdate"];
                };
            };
        };
    };
    homeowner_association_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this homeowner association. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedHomeownerAssociationUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedHomeownerAssociationUpdate"];
                "multipart/form-data": components["schemas"]["PatchedHomeownerAssociationUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeownerAssociationUpdate"];
                };
            };
        };
    };
    homeowner_association_apartments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this homeowner association. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Apartment"];
                };
            };
        };
    };
    homeowner_association_cases_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this homeowner association. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseList"];
                };
            };
        };
    };
    homeowner_association_communication_notes_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this homeowner association. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeownerAssociationCommunicationNote"][];
                };
            };
        };
    };
    homeowner_association_communication_notes_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this homeowner association. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HomeownerAssociationCommunicationNoteCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["HomeownerAssociationCommunicationNoteCreate"];
                "multipart/form-data": components["schemas"]["HomeownerAssociationCommunicationNoteCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeownerAssociationCommunicationNote"];
                };
            };
        };
    };
    homeowner_association_communication_notes_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this homeowner association. */
                id: number;
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    homeowner_association_communication_notes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this homeowner association. */
                id: number;
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedHomeownerAssociationCommunicationNoteUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedHomeownerAssociationCommunicationNoteUpdate"];
                "multipart/form-data": components["schemas"]["PatchedHomeownerAssociationCommunicationNoteUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeownerAssociationCommunicationNote"];
                };
            };
        };
    };
    homeowner_association_contacts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this homeowner association. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeownerAssociation"];
                };
            };
        };
    };
    homeowner_association_contacts_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this homeowner association. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HomeownerAssociation"];
                "application/x-www-form-urlencoded": components["schemas"]["HomeownerAssociation"];
                "multipart/form-data": components["schemas"]["HomeownerAssociation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeownerAssociation"];
                };
            };
        };
    };
    homeowner_association_contacts_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this homeowner association. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HomeownerAssociation"];
                "application/x-www-form-urlencoded": components["schemas"]["HomeownerAssociation"];
                "multipart/form-data": components["schemas"]["HomeownerAssociation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeownerAssociation"];
                };
            };
        };
    };
    homeowner_association_delete_contact_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
                /** @description A unique integer value identifying this homeowner association. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    homeowner_association_subsidy_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this homeowner association. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubsidyItem"][];
                };
            };
            /** @description No response body */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    homeowner_association_import_course_participants_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseParticipantImport"];
                "application/x-www-form-urlencoded": components["schemas"]["CourseParticipantImport"];
                "multipart/form-data": components["schemas"]["CourseParticipantImport"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
        };
    };
    homeowner_association_import_letters_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LetterImport"];
                "application/x-www-form-urlencoded": components["schemas"]["LetterImport"];
                "multipart/form-data": components["schemas"]["LetterImport"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
        };
    };
    homeowner_association_search_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeownerAssociation"];
                };
            };
        };
    };
    neighborhoods_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNeighborhoodList"];
                };
            };
        };
    };
    neighborhoods_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Buurt. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Neighborhood"];
                };
            };
        };
    };
    tasks_list: {
        parameters: {
            query?: {
                /**
                 * @description * `Energieadvies` - ENERGY_ADVICE
                 *     * `Haalbaarheidsonderzoek` - HBO
                 *     * `Energieadvies (OUD)` - OLD_ENERGY_ADVICE
                 *     * `Zon-Advies (OUD)` - OLD_SOLAR_ADVICE
                 */
                advice_type?: "Energieadvies" | "Energieadvies (OUD)" | "Haalbaarheidsonderzoek" | "Zon-Advies (OUD)" | null;
                advisor?: string[];
                /**
                 * @description * `Advies` - ADVICE
                 *     * `Activatieteam` - ACTIVATIONTEAM
                 */
                application_type?: "Activatieteam" | "Advies";
                district?: string[];
                /** @description HOA has <= 12 apartments */
                is_small_hoa?: boolean;
                name?: string;
                neighborhood?: string[];
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                request_date_range_after?: string;
                request_date_range_before?: string;
                /** @description Search */
                search?: string;
                status?: string[];
                wijk?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCaseUserTaskListList"];
                };
            };
        };
    };
    tasks_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this case user task. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseUserTaskList"];
                };
            };
        };
    };
    tasks_names_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseUserTaskList"];
                };
            };
        };
    };
    wijken_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedWijkList"];
                };
            };
        };
    };
    wijken_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Wijk. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wijk"];
                };
            };
        };
    };
}
